name: metrics-api
services:
    backend:
        build:
            context: .
            target: ${STAGE}
        networks:
            - client-server
        ports:
            - 7654:3000
        develop:
            watch:
                - action: sync
                  path: .
                  target: /usr/local/app

networks:
    client-server: {}
