name: metrics-api
services:
    backend:
        build:
            context: .
            target: ${STAGE}
        networks:
            - server-side
        ports:
            - 7654:3000
        develop:
            watch:
                - action: sync
                  path: .
                  target: /usr/local/app
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        networks:
            - server-side
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - "7070:3000"
        networks:
            - server-side
        environment:
            - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
            - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    node_exporter:
        image: quay.io/prometheus/node-exporter:latest
        container_name: node_exporter
        command:
            - "--path.rootfs=/host"
        ports:
            - "9100:9100"
        networks:
            - server-side
        restart: unless-stopped
        volumes:
            - "/:/host:ro,rslave"

networks:
    server-side: {}
