{
 "title": "Dcote website activity",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Активные пользователи сайта",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(active_site_users_global{job=\"backend\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Активные сессии сайта",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(active_site_sessions_global{job=\"backend\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Открытые вкладки сайта",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(active_site_tabs_global{job=\"backend\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Пользователи сайта по страницам",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (page) (active_site_users{job=\"backend\"}) > 0)",
     "legendFormat": "{{page}}"
    }
   ]
  },
  {
   "title": "Вкладки сайта по страницам",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (page) (active_site_tabs{job=\"backend\"}) > 0)",
     "legendFormat": "{{page}}"
    }
   ]
  }
 ]
}