{
 "title": "Dcote video player",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Онлайн зрители",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(active_viewers{job=\"backend\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Онлайн зрители график",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(active_viewers{job=\"backend\"}) or vector(0)",
     "legendFormat": "Онлайн зрители"
    }
   ]
  },
  {
   "title": "Всего просмотров",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(video_views_total{job=\"backend\"}[$__range]))) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Авг время просмотра",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(increase(viewing_duration_seconds_sum{job=\"backend\"}[$__range]))\r\n  /\r\n  (sum(increase(viewing_duration_seconds_count{job=\"backend\"}[$__range])) > 0)\r\n)\r\nor vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сумма всех времени просмотра",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(viewing_duration_seconds_sum{job=\"backend\"}[$__range])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Страны",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(round(sum by (country) (increase(video_views_total{job=\"backend\"}[$__range]))) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Страны pie chart",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(round(sum by (country) (increase(video_views_total{job=\"backend\"}[$__range]))) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сезоны",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(round(sum by (season) (increase(video_views_total{job=\"backend\"}[$__range]))) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cезоны pie chart",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(round(sum by (season) (increase(video_views_total{job=\"backend\"}[$__range]))) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Тип озвучки",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(round(sum by (voice) (increase(video_views_total{job=\"backend\"}[$__range]))) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Субтитры",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(subtitles_enabled_total{job=\"backend\"}[$__range]))) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Топ 10 серий",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "topk(10, (round(sum by (season, episode) (increase(video_views_total{job=\"backend\"}[$__range]))) > 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Озвучки по сериям",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sort_desc((round(sum by (season, episode, voice) (increase(video_views_total{job=\"backend\"}[$__range]))) > 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Субтитры по сериям",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sort_desc((round(sum by (season, episode) (increase(subtitles_enabled_total{job=\"backend\"}[$__range]))) > 0))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}